runtime: custom
vm: true

handlers:
- url: /.*
  script: this field is required, but ignored
  secure: always

runtime_config:
   jdk: openjdk8


health_check:
  enable_health_check: False
  check_interval_sec: 60
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2
  restart_threshold: 60

manual_scaling:
  instances: 2
